
---
- hosts: eos
  tasks:
  - name: Gather vlans facts from the device
      ip_address: '10.1.101.28'
      username: 'admin'
      password: 'P@ssw0rd'
   
   arista.eos.eos_vlans:
     state: gathered

  - name: Merge given VLAN attributes with device configuration
    arista.eos.eos_vlans:
     config:
      - vlan_id: 56
        state: active
        name: fromansible1
     state: merged

  - name: always save config to startup-config
    arista.eos.eos_config:
     save_when: always
